### ISSUE TITLE
Product Listing: retain the sidebar menu in all  product pages

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#131] opened 2016-06-14 08:20 UTC
![image](https://cloud.githubusercontent.com/assets/17717843/16035861/e46d6a06-324b-11e6-9050-6a660c4ef045.png)

**Comment by jsemblantetitanweb** [comment] 2016-06-15 09:29
Since the sidebar depends on the list of sub categories that the category contains, this is not a bug. Categories without sub categories are normally displaying such "NO CATEGORIES" in the sidebar for it can't display anything.

**Comment by roseliesromeo** [comment] 2016-06-29 05:12
Sidebar should display in category/subcategory and single page as per design.

**Comment by roseliesromeo** [comment] 2016-07-01 02:02
Not fixed in single pages. See bug #159

**Closed** 2016-07-08 09:04 UTC
Labels: bug, fixed
